# Generated by Django 4.1.4 on 2022-12-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(default="not provided", max_length=255),
        ),
    ]
