# Generated by Django 4.1.4 on 2022-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_resualt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resualt",
            old_name="rule_name",
            new_name="resualt_name",
        ),
        migrations.RemoveField(
            model_name="resualt",
            name="rule_function",
        ),
        migrations.AddField(
            model_name="resualt",
            name="rule_function",
            field=models.ManyToManyField(to="rules.rule"),
        ),
    ]
