# Generated by Django 4.1.4 on 2022-12-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("course_credit", models.IntegerField()),
            ],
        ),
    ]
