# Generated by Django 4.1.4 on 2022-12-27 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Department", "0002_coursemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Department.departmentmodel",
                    ),
                ),
            ],
        ),
    ]
