# Generated by Django 4.1.4 on 2022-12-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Department", "0004_chartmodel_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentmodel",
            name="department_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
