# Generated by Django 4.1.4 on 2022-12-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Department", "0007_coursemodel_dependencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodel",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, null=True, to="Department.coursemodel"
            ),
        ),
    ]
