# Generated by Django 4.1.4 on 2022-12-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Department", "0008_alter_coursemodel_dependencies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChartModel",
            new_name="Chart",
        ),
        migrations.RenameModel(
            old_name="CourseModel",
            new_name="Course",
        ),
        migrations.RenameModel(
            old_name="DepartmentModel",
            new_name="Department",
        ),
    ]
